# Generated by Django 5.1.4 on 2024-12-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_registrationlink_alumniprofile_registration_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationlink',
            name='created_by',
        ),
        migrations.AddField(
            model_name='registrationlink',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registrationlink',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
